server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.146.121:3306/weather?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: ctt
    password: ctt2011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


#访问地址：http://192.168.147.170:7080/html/login.html
#日志
#logging:
#  file: D:/Data/JavaRepository/newapp/newapp.log
#
logging:
    level:
      #显示SQL
      mapper: debug
      #打印日志
      com.eastday: debug

#获取天气信息url
weather_mini_url: http://wthrcdn.etouch.cn/weather_mini
specicalcity : 上海
